# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/madscientist/untitled1/clients.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(150, 150, 591, 351))
        self.table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.addUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.addUserButton.setGeometry(QtCore.QRect(590, 110, 112, 32))
        self.addUserButton.setObjectName("addUserButton")
        self.searchUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchUserButton.setGeometry(QtCore.QRect(480, 110, 112, 32))
        self.searchUserButton.setObjectName("searchUserButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "شناسه کاربر"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "نام"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "نام خانوادگی"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "شماره تلفن"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "آدرس"))
        self.addUserButton.setText(_translate("MainWindow", "افزودن کاربر"))
        self.searchUserButton.setText(_translate("MainWindow", "جستجوی کاربر"))
        self.label.setText(_translate("MainWindow", "منوی کاربران"))
