# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/madscientist/untitled1/worker_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(448, 429)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(328, 270, 51, 26))
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 70, 261, 166))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.nameText.setObjectName("nameText")
        self.verticalLayout_2.addWidget(self.nameText)
        self.lnameText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lnameText.setObjectName("lnameText")
        self.verticalLayout_2.addWidget(self.lnameText)
        self.phoneText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.phoneText.setObjectName("phoneText")
        self.verticalLayout_2.addWidget(self.phoneText)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(147, 39, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(60, 240, 311, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(70, 350, 121, 20))
        self.label_6.setObjectName("label_6")
        self.skillsText = QtWidgets.QPlainTextEdit(Dialog)
        self.skillsText.setGeometry(QtCore.QRect(60, 260, 261, 81))
        self.skillsText.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.skillsText.setObjectName("skillsText")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "مهارت ها"))
        self.label.setText(_translate("Dialog", "نام"))
        self.label_2.setText(_translate("Dialog", "نام خانوادگی"))
        self.label_3.setText(_translate("Dialog", "شماره تلفن"))
        self.label_5.setText(_translate("Dialog", "افزودن خدمات دهنده"))
        self.label_6.setText(_translate("Dialog", "هر مهارت در یک خط"))
        self.skillsText.setPlainText(_translate("Dialog", "ldkjldfj\n"
"dfkj"))
